[phases.setup]
nixPkgs = ['python39']
aptPkgs = ['python3-dev', 'python3-pip', 'python3-venv']

[phases.install]
cmds = [
  'python -m venv --copies .venv',
  '. .venv/bin/activate',
  'pip install --upgrade pip',
  'pip install wheel',
  'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'gunicorn app:app' 